export const StaticData = {
    Meta_title:"Find the nearest Carpetright store near you | Carpet, Flooring and Beds",
    Meta_description:"Carpetright is the UK's largest retailer of carpets, flooring and beds. Carpetright has 350 UK stores and an extensive online range of carpets, vinyl, laminate, rugs and beds.",
    
    locator_breadcrumb:"Store Locator",
    FindLocationtext:"Find a Location",
    Usemylocation:"Use my location",
    Search:"Search",
    Brandname:"Carpetright",
    miles:"miles",
    tempClosed:"Temporarily Closed",
    StoreDetailbtn:"go to store",
    Storehighlight:"Store Highlights",
    Days:"Days",
    Hours:"Hours",
    Minutes:"Minutes",
    Seconds:"Seconds",
    getDirection:"Get Directions",
    AllRegion:"All Regions of",
    NearStoretext:"NEARBY LOCATIONS",
    AllLocationtext:"View All Location",
    PagenotFound:"404 - Page Not Found",
    cantfind_page:"We're really sorry, we can't find the page you're looking for",
    Youcouldtry:"You could try",
    Previuspage:"Going back to the previous page",
    homePage:"Going back to the homepage",
    StoreFinder:"Store Finder",
    cookie:"cookies policy",
    Closed:"Closed",
    DayofWeek:"Day of the Week",
    Reopenmessage:"Message - The store is temporarily closed. It will reopen at",
    Address:"Address",
    Telephone:"Telephone",
    Holdiay:"Holdiday Hours",
    }